version: "3.9"
services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3002:3002
    volumes:
      - .:/app
      - .:/assets:${ASSETS_DIRECTORY}
      - .:/var/log:${LOG_DIRECTORY}
    depends_on:
      - db
  db:
    build:
      dockerfile: ./pgx_ulid/Dockerfile
    container_name: "db"
    ports:
      - "54333:5432"
    restart: no
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  app:

