services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3002:3002
    volumes:
      - .:/app
      - .:/assets:/app/assets
      - .:/public:/app/public
      - .:/var/log:/app/var/log
      - .:/var/assets:/app/var/assets
    depends_on:
      - db
  db:
    image: "postgres"
#    build:
#      dockerfile: ./pgx_ulid/Dockerfile
    container_name: "db"
    ports:
      - "54333:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
#    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  app:

