services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "curl -i http://api:3002/api/v1/health/full-health || { echo 'Health check failed with code $?'; exit 1; }" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 3002:3002
    volumes:
      - .:/app
      - .:/assets:/app/assets
      - .:/public:/app/public
      - .:/var/log:/app/var/log
      - .:/var/assets:/app/var/assets
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 10s
      timeout: 5s
      retries: 5
    #    build:
    #      dockerfile: ./pgx_ulid/Dockerfile
    container_name: "db"
    ports:
      - "54333:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
#    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  app:
